name: Badges

on:
  push:
    branches: [main]

jobs:
  badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - name: Commit badges
        run: |
          npm run test:badges
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          git config --local user.email ${{ secrets.USER_EMAIL }}
          git config --local user.name "${{ secrets.USER_NAME }}"
          git add coverage
          git diff-index --quiet HEAD || git commit -m "Add coverage badges"
          git push
